version: '3'

services:
  app:
    container_name: airtel-mock
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - network_tmobs
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always

networks:
  network_tmobs:
    external: true
    name: network_tmobs
